require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompanyPoliciesController do

  # This should return the minimal set of attributes required to create a valid
  # CompanyPolicy. As you add validations to CompanyPolicy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompanyPoliciesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all company_policies as @company_policies" do
      company_policy = CompanyPolicy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:company_policies).should eq([company_policy])
    end
  end

  describe "GET show" do
    it "assigns the requested company_policy as @company_policy" do
      company_policy = CompanyPolicy.create! valid_attributes
      get :show, {:id => company_policy.to_param}, valid_session
      assigns(:company_policy).should eq(company_policy)
    end
  end

  describe "GET new" do
    it "assigns a new company_policy as @company_policy" do
      get :new, {}, valid_session
      assigns(:company_policy).should be_a_new(CompanyPolicy)
    end
  end

  describe "GET edit" do
    it "assigns the requested company_policy as @company_policy" do
      company_policy = CompanyPolicy.create! valid_attributes
      get :edit, {:id => company_policy.to_param}, valid_session
      assigns(:company_policy).should eq(company_policy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompanyPolicy" do
        expect {
          post :create, {:company_policy => valid_attributes}, valid_session
        }.to change(CompanyPolicy, :count).by(1)
      end

      it "assigns a newly created company_policy as @company_policy" do
        post :create, {:company_policy => valid_attributes}, valid_session
        assigns(:company_policy).should be_a(CompanyPolicy)
        assigns(:company_policy).should be_persisted
      end

      it "redirects to the created company_policy" do
        post :create, {:company_policy => valid_attributes}, valid_session
        response.should redirect_to(CompanyPolicy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved company_policy as @company_policy" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyPolicy.any_instance.stub(:save).and_return(false)
        post :create, {:company_policy => {  }}, valid_session
        assigns(:company_policy).should be_a_new(CompanyPolicy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyPolicy.any_instance.stub(:save).and_return(false)
        post :create, {:company_policy => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested company_policy" do
        company_policy = CompanyPolicy.create! valid_attributes
        # Assuming there are no other company_policies in the database, this
        # specifies that the CompanyPolicy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CompanyPolicy.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => company_policy.to_param, :company_policy => { "these" => "params" }}, valid_session
      end

      it "assigns the requested company_policy as @company_policy" do
        company_policy = CompanyPolicy.create! valid_attributes
        put :update, {:id => company_policy.to_param, :company_policy => valid_attributes}, valid_session
        assigns(:company_policy).should eq(company_policy)
      end

      it "redirects to the company_policy" do
        company_policy = CompanyPolicy.create! valid_attributes
        put :update, {:id => company_policy.to_param, :company_policy => valid_attributes}, valid_session
        response.should redirect_to(company_policy)
      end
    end

    describe "with invalid params" do
      it "assigns the company_policy as @company_policy" do
        company_policy = CompanyPolicy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyPolicy.any_instance.stub(:save).and_return(false)
        put :update, {:id => company_policy.to_param, :company_policy => {  }}, valid_session
        assigns(:company_policy).should eq(company_policy)
      end

      it "re-renders the 'edit' template" do
        company_policy = CompanyPolicy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyPolicy.any_instance.stub(:save).and_return(false)
        put :update, {:id => company_policy.to_param, :company_policy => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested company_policy" do
      company_policy = CompanyPolicy.create! valid_attributes
      expect {
        delete :destroy, {:id => company_policy.to_param}, valid_session
      }.to change(CompanyPolicy, :count).by(-1)
    end

    it "redirects to the company_policies list" do
      company_policy = CompanyPolicy.create! valid_attributes
      delete :destroy, {:id => company_policy.to_param}, valid_session
      response.should redirect_to(company_policies_url)
    end
  end

end
