require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpaceUsersController do

  # This should return the minimal set of attributes required to create a valid
  # SpaceUser. As you add validations to SpaceUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpaceUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all space_users as @space_users" do
      space_user = SpaceUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:space_users).should eq([space_user])
    end
  end

  describe "GET show" do
    it "assigns the requested space_user as @space_user" do
      space_user = SpaceUser.create! valid_attributes
      get :show, {:id => space_user.to_param}, valid_session
      assigns(:space_user).should eq(space_user)
    end
  end

  describe "GET new" do
    it "assigns a new space_user as @space_user" do
      get :new, {}, valid_session
      assigns(:space_user).should be_a_new(SpaceUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested space_user as @space_user" do
      space_user = SpaceUser.create! valid_attributes
      get :edit, {:id => space_user.to_param}, valid_session
      assigns(:space_user).should eq(space_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpaceUser" do
        expect {
          post :create, {:space_user => valid_attributes}, valid_session
        }.to change(SpaceUser, :count).by(1)
      end

      it "assigns a newly created space_user as @space_user" do
        post :create, {:space_user => valid_attributes}, valid_session
        assigns(:space_user).should be_a(SpaceUser)
        assigns(:space_user).should be_persisted
      end

      it "redirects to the created space_user" do
        post :create, {:space_user => valid_attributes}, valid_session
        response.should redirect_to(SpaceUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved space_user as @space_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpaceUser.any_instance.stub(:save).and_return(false)
        post :create, {:space_user => {  }}, valid_session
        assigns(:space_user).should be_a_new(SpaceUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpaceUser.any_instance.stub(:save).and_return(false)
        post :create, {:space_user => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested space_user" do
        space_user = SpaceUser.create! valid_attributes
        # Assuming there are no other space_users in the database, this
        # specifies that the SpaceUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpaceUser.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => space_user.to_param, :space_user => { "these" => "params" }}, valid_session
      end

      it "assigns the requested space_user as @space_user" do
        space_user = SpaceUser.create! valid_attributes
        put :update, {:id => space_user.to_param, :space_user => valid_attributes}, valid_session
        assigns(:space_user).should eq(space_user)
      end

      it "redirects to the space_user" do
        space_user = SpaceUser.create! valid_attributes
        put :update, {:id => space_user.to_param, :space_user => valid_attributes}, valid_session
        response.should redirect_to(space_user)
      end
    end

    describe "with invalid params" do
      it "assigns the space_user as @space_user" do
        space_user = SpaceUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpaceUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => space_user.to_param, :space_user => {  }}, valid_session
        assigns(:space_user).should eq(space_user)
      end

      it "re-renders the 'edit' template" do
        space_user = SpaceUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpaceUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => space_user.to_param, :space_user => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested space_user" do
      space_user = SpaceUser.create! valid_attributes
      expect {
        delete :destroy, {:id => space_user.to_param}, valid_session
      }.to change(SpaceUser, :count).by(-1)
    end

    it "redirects to the space_users list" do
      space_user = SpaceUser.create! valid_attributes
      delete :destroy, {:id => space_user.to_param}, valid_session
      response.should redirect_to(space_users_url)
    end
  end

end
